name: EAS Build (optional)

on:
  workflow_dispatch:
    inputs:
      profile:
        description: 'EAS build profile (development, preview, production)'
        required: false
        default: 'development'

jobs:
  build:
    if: ${{ secrets.EXPO_TOKEN != '' }}
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup EAS
        run: npm i -g eas-cli

      - name: EAS login
        run: eas whoami || eas login --token $EXPO_TOKEN
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: EAS build
        run: eas build --platform all --non-interactive --profile ${{ github.event.inputs.profile || 'development' }}
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

